services:
  places-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - places-pgdata:/var/lib/postgresql/data

  places-api:
    build:
      context: .
      dockerfile: Containerfile.prod

    depends_on:
      places-db:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      CONNECTION_STRING: "Host=places-db;Database=appdb;Username=appuser;Password=apppass"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      JWT__KEY: "cambiar-por-clave-segura"
      JWT__ExpiresHours: "24"
      BaseImageUrl: "https://places-back.in4ind.fyi/api/images"

volumes:
  places-pgdata:
